version: "3"
services:
  server:
    build: ./node-js-jwt-auth
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1284
      POSTGRES_DB: testdb
  client:
    build: ./react-jwt-auth
    ports:
      - "80:80"